global:
  resolve_timeout: 5m
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertas@tudominio.com'
  smtp_auth_username: 'alertas@tudominio.com'
  smtp_auth_password: 'TU_SMTP_PASSWORD'

route:
  receiver: 'team-email'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'team-email'
    email_configs:
      - to: 'miemail@dominio.com'
        send_resolved: true
