global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'apps'
    metrics_path: /metrics
    static_configs:
      - targets: ['app1:5000', 'app2:5000']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
