groups:
  - name: lab-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Uso de CPU alto en {{ $labels.instance }}"
          description: "CPU > 80% por más de 2 minutos"

      - alert: MySQLDown
        expr: up{job="mysql"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MySQL no disponible"
          description: "El exporter de MySQL no responde"

      - alert: AppInstanceDown
        expr: sum(up{job="apps"}) == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Instancia de app caída"
          description: "Todas las instancias de la app están abajo"

      - alert: HighMySQLConnections
        expr: mysql_global_status_threads_connected > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Conexiones MySQL altas"
          description: "Conexiones activas a MySQL > 80"

      - alert: LowMemoryHost
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 15
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Memoria disponible baja en host"
          description: "Memoria disponible < 15% en {{ $labels.instance }}"
